import type { Metadata } from "next";
import { Roboto, Londrina_Outline } from "next/font/google";
import "./globals.css";

const roboto = Roboto({ subsets: ["latin"], weight: ['400','500','700','900'] });
const londrinaOutline = Londrina_Outline({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Portifólio Dev.Lucas Barragana",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} ${londrinaOutline.className}`}>
        {children}
      </body>
    </html>
  );
}
